import {
  Wallet,
  CreditCard,
  PiggyBank,
  Landmark,
  TrendingUp,
  LineChart,
  BarChart3,
  PieChart,
  Coins,
  Banknote,
  Building2,
  ShieldCheck,
  Gem,
  Home,
  Car,
  Briefcase,
  GraduationCap,
  Plane,
  Gift,
  Heart,
  Umbrella,
  Lock,
  Star,
  Rocket,
  HandCoins,
  Vault,
  WalletCards,
  CircleDollarSign,
  type LucideIcon,
} from 'lucide-react';

export const ACCOUNT_ICONS: Record<string, LucideIcon> = {
  wallet: Wallet,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  coins: Coins,
  banknote: Banknote,
  building: Building2,
  shield: ShieldCheck,
  gem: Gem,
  home: Home,
  car: Car,
  briefcase: Briefcase,
  graduation: GraduationCap,
  plane: Plane,
  gift: Gift,
  heart: Heart,
  umbrella: Umbrella,
  lock: Lock,
  star: Star,
  rocket: Rocket,
  'hand-coins': HandCoins,
  vault: Vault,
  'wallet-cards': WalletCards,
  'dollar-circle': CircleDollarSign,
};

export const ACCOUNT_ICON_CHOICES = Object.keys(ACCOUNT_ICONS);
